package com.kmedtech.studentcrud.service;

import com.kmedtech.studentcrud.dto.StudentDTO;
import com.kmedtech.studentcrud.dto.StudentMapper;
import com.kmedtech.studentcrud.model.Student;
import com.kmedtech.studentcrud.repository.StudentRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.util.List;

@Service
public class StudentService {

    private final StudentRepository studentRepository;

    // Constructor injection
    public StudentService(StudentRepository studentRepository) {
        this.studentRepository = studentRepository;
    }

    // Helper method to find the Student Entity internally
    private Student findStudentEntityById(Long id) {
        return studentRepository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND, "Student not found with id: " + id));
    }

    public String getStudentEmail(Long id) {

        Student student = studentRepository.findById(id)
                .orElseThrow(() ->
                        new RuntimeException("Student Not Found"));

        return student.getEmail();
    }

    public List<StudentDTO> getStudentsByFirstName(String firstName) {
        return studentRepository.findByFirstName(firstName)
                .stream()
                .map(StudentMapper::toDTO)
                .toList();
    }

    public List<StudentDTO> getStudentsByLastName(String lastName) {
        return studentRepository.findByLastName(lastName)
                .stream()
                .map(StudentMapper::toDTO)
                .toList();
    }

    public List<StudentDTO> getStudentsByAge(Integer age){
        return studentRepository.findByAge(age)
                .stream()
                .map(StudentMapper::toDTO)
                .toList();
    }

    public List<StudentDTO> getStudentsByAgeGreaterThan(Integer age){

        return studentRepository.findByAgeGreaterThan(age)
                .stream()
                .map(StudentMapper::toDTO)
                .toList();
    }

    // Retrieve all students as DTOs
    public List<StudentDTO> getAllStudents() {
        return studentRepository.findAll()
                .stream()
                .map(StudentMapper::toDTO)
                .toList();
    }

    public Page<StudentDTO> getStudents(int page, int size) {
        Pageable pageable = PageRequest.of(page,size, Sort.by("age").ascending());
        return studentRepository.findAll(pageable)
                .map(StudentMapper::toDTO);

    }

    // Retrieve a student by ID as DTO
    public StudentDTO getStudentById(Long id) {
        Student student = findStudentEntityById(id);
        return StudentMapper.toDTO(student);
    }

//    retrieving students by firstname
//
//    public List<Student> getStudentsByFirstName(String firstName){
//        return studentRepository.findByFirstName(firstName);
//    }
//    public List<Student> getStudentsByLastName(String lastName){
//        return studentRepository.findByLastName(lastName);
//    }
//    public List<Student> getStudentsByAge(Integer age){
//        return studentRepository.findByAge(age);
//    }
//    public List<Student> getStudentsByAgeGreaterThan(Integer age){
//        return studentRepository.findByAgeGreaterThan(age);
//    }

    // Create a new student from DTO and return DTO
    public StudentDTO createStudent(StudentDTO studentDTO) {
        if (studentRepository.findByEmail(studentDTO.getEmail()).isPresent()) {
            throw new ResponseStatusException(
                    HttpStatus.BAD_REQUEST, "Email already exists: " + studentDTO.getEmail());
        }
        
        Student student = StudentMapper.toEntity(studentDTO);
        student.setId(null); // Ensure ID is generated by database
        Student savedStudent = studentRepository.save(student);
        return StudentMapper.toDTO(savedStudent);
    }



    // Update an existing student using DTO and return DTO
    public StudentDTO updateStudent(Long id, StudentDTO studentDetailsDTO) {
        Student student = findStudentEntityById(id);

        if (!student.getEmail().equalsIgnoreCase(studentDetailsDTO.getEmail()) &&
                studentRepository.findByEmail(studentDetailsDTO.getEmail()).isPresent()) {
            throw new ResponseStatusException(
                    HttpStatus.BAD_REQUEST, "Email already exists: " + studentDetailsDTO.getEmail());
        }

        student.setFirstName(studentDetailsDTO.getFirstName());
        student.setLastName(studentDetailsDTO.getLastName());
        student.setEmail(studentDetailsDTO.getEmail());
        student.setAge(studentDetailsDTO.getAge());

        Student updatedStudent = studentRepository.save(student);
        return StudentMapper.toDTO(updatedStudent);
    }

    // Delete a student by ID
    public void deleteStudent(Long id) {
        Student student = findStudentEntityById(id);
        studentRepository.delete(student);
    }
}
